name: Check source integrations

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/admin-request.yml
    with:
      operation: integrations
    secrets: inherit
